"""BibTeX export parser."""

from __future__ import annotations

import re
from pathlib import Path

from citationer.models.record import Author, DocType, Record
from citationer.parsers.base import BaseParser


class BibTeXParser(BaseParser):
    """Parser for BibTeX (.bib) files.

    Handles standard BibTeX entries generated by common reference
    managers (Zotero, Mendeley, EndNote, etc.).
    """

    @property
    def source_name(self) -> str:
        return "BibTeX"

    def detect(self, filepath: Path) -> bool:
        if filepath.suffix.lower() != ".bib":
            return False

        try:
            with open(filepath, encoding="utf-8-sig", errors="ignore") as f:
                head = f.read(4000)
            # BibTeX entries start with @type{key,
            return bool(re.search(r"^@\w+\{", head, re.MULTILINE))
        except Exception:
            return False

    def parse(self, filepath: Path) -> list[Record]:
        with open(filepath, encoding="utf-8-sig", errors="ignore") as f:
            text = f.read()

        records: list[Record] = []

        # Split on @ entries (each entry starts with @type{key,)
        entries = re.split(r"(?=\n?@\w+\{)", text)
        for entry in entries:
            entry = entry.strip()
            if not entry or not entry.startswith("@"):
                continue

            try:
                rec = self._parse_entry(entry, filepath.name)
                if rec:
                    records.append(rec)
            except Exception:
                continue

        return records

    def _parse_entry(self, entry: str, source_file: str) -> Record | None:
        # Parse entry header: @type{key,
        m = re.match(r"@(\w+)\{([^,]*),", entry)
        if not m:
            return None

        bibtex_type = m.group(1).lower()
        fields = self._extract_fields(entry)

        # Title
        title = fields.get("title", "").strip()
        if not title:
            return None

        # Authors: "Last, First and Last, First"
        authors = self._parse_authors(fields.get("author", ""))

        # Year
        year: int | None = None
        y = fields.get("year", "")
        m = re.search(r"(\d{4})", y)
        if m:
            try:
                year = int(m.group(1))
            except ValueError:
                pass

        # Journal / Booktitle
        journal = fields.get("journal", "").strip() or fields.get("booktitle", "").strip() or None

        # Volume, Issue, Pages
        volume = fields.get("volume", "").strip() or None
        issue = fields.get("number", "").strip() or None
        pages = fields.get("pages", "").strip() or None

        # DOI
        doi = fields.get("doi", "").strip() or None

        # Keywords
        keywords: list[str] = []
        kw = fields.get("keywords", "")
        if kw:
            keywords = [k.strip() for k in re.split(r"[,;]+", kw) if k.strip()]

        # Abstract
        abstract = fields.get("abstract", "").strip() or None

        # Language
        language = fields.get("language", "").strip().lower()[:3] or None

        # Doc type
        doc_type = self._map_type(bibtex_type)

        return Record(
            title=title,
            authors=authors,
            year=year,
            journal=journal,
            volume=volume,
            issue=issue,
            pages=pages,
            doi=doi,
            abstract=abstract,
            keywords=keywords,
            language=language or "en",
            doc_type=doc_type,
            source_database="BibTeX",
            source_file=source_file,
        )

    def _extract_fields(self, entry: str) -> dict[str, str]:
        """Extract key = {value} pairs from a BibTeX entry."""
        fields: dict[str, str] = {}
        # Match key = {value} or key = value
        for m in re.finditer(
            r"(\w+)\s*=\s*\{([^}]*)\}", entry, re.DOTALL
        ):
            fields[m.group(1).lower()] = m.group(2).strip()
        # Also match key = value (non-braced)
        for m in re.finditer(r"(\w+)\s*=\s*\"([^\"]*)\"", entry, re.DOTALL):
            fields.setdefault(m.group(1).lower(), m.group(2).strip())
        return fields

    @staticmethod
    def _parse_authors(raw: str) -> list[Author]:
        if not raw:
            return []
        names = [n.strip() for n in raw.split(" and ") if n.strip()]
        authors = []
        for i, name in enumerate(names):
            surname, given = name, None
            if "," in name:
                parts = name.split(",", 1)
                surname = parts[0].strip()
                given = parts[1].strip() if len(parts) > 1 else None
            authors.append(Author(
                full_name=name, surname=surname,
                given_name=given, order=i + 1,
            ))
        return authors

    @staticmethod
    def _map_type(bibtex_type: str) -> DocType:
        t = bibtex_type.lower()
        if "article" in t:
            return DocType.ARTICLE
        if "book" in t:
            return DocType.BOOK
        if "incollection" in t or "inproceedings" in t:
            return DocType.BOOK_CHAPTER
        if "proceedings" in t:
            return DocType.CONFERENCE
        if "phd" in t or "master" in t or "thesis" in t:
            return DocType.THESIS
        if "misc" in t:
            return DocType.OTHER
        return DocType.OTHER
