"""Report generation commands — one-click Markdown/HTML reports."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console

from citationer.analysis.network import NetworkEngine
from citationer.analysis.stats import StatsEngine
from citationer.analysis.text import TextEngine
from citationer.utils.db_loader import get_records

app = typer.Typer(
    name="report",
    help="报告生成",
    no_args_is_help=True,
)

console = Console()

_get_records = get_records


def _build_markdown(records) -> str:
    """Build a comprehensive Markdown report from all analysis engines."""
    engine = StatsEngine(records)
    overview = engine.overview()
    yearly = engine.yearly()
    top_journals = engine.journals(top_n=10)
    top_authors = engine.authors(top_n=10)

    text = TextEngine(records)
    kw_result = text.keywords(top_n=10)
    topic_result = text.topics(num_topics=5, method="lda")

    net = NetworkEngine(records)
    cooc = net.keyword_cooccurrence(top_n=20, threshold=2)

    sections = []

    # Header
    sections.append("# Citationer Analysis Report\n")
    sections.append(f"**Total records**: {overview.total_records}  ·  "
                    f"**Year range**: {overview.year_min}–{overview.year_max}  ·  "
                    f"**h-index**: {overview.h_index}\n")

    # Overview
    sections.append("## Overview\n")
    sections.append("| Metric | Value |")
    sections.append("|--------|-------|")
    sections.append(f"| Total records | {overview.total_records} |")
    sections.append(f"| Unique authors | {overview.num_authors} |")
    sections.append(f"| Journals | {overview.num_journals} |")
    sections.append(f"| Institutions | {overview.num_institutions} |")
    sections.append(f"| Solo rate | {overview.solo_rate:.1%} |")
    sections.append(f"| Avg citations | {overview.avg_citations:.1f} |")
    sections.append(f"| h-index | {overview.h_index} |\n")

    # Yearly trend
    if yearly.year_counts:
        sections.append("## Publication Trend\n")
        sections.append("| Year | Publications |")
        sections.append("|------|-------------|")
        for y in sorted(yearly.year_counts)[-10:]:
            sections.append(f"| {y} | {yearly.year_counts[y]} |")
        sections.append("")

    # Top journals
    if top_journals.items:
        sections.append("## Top Journals\n")
        sections.append("| # | Journal | Count |")
        sections.append("|---|---------|-------|")
        for i, (name, count) in enumerate(top_journals.items, 1):
            sections.append(f"| {i} | {name} | {count} |")
        sections.append("")

    # Top authors
    if top_authors.top_authors.items:
        sections.append("## Top Authors\n")
        sections.append("| # | Author | Papers | h-index |")
        sections.append("|---|--------|--------|---------|")
        h_dict = dict(top_authors.author_h_index)
        for i, (name, count) in enumerate(top_authors.top_authors.items, 1):
            h = h_dict.get(name, 0)
            sections.append(f"| {i} | {name} | {count} | {h} |")
        sections.append("")

    # Keywords
    if kw_result.top_keywords:
        sections.append("## Top Keywords\n")
        sections.append("| # | Keyword | Frequency |")
        sections.append("|---|---------|-----------|")
        for i, (kw, cnt) in enumerate(kw_result.top_keywords[:10], 1):
            sections.append(f"| {i} | {kw} | {cnt} |")
        sections.append("")

    # Topic modeling
    if topic_result.topics:
        sections.append("## Topic Modeling (LDA)\n")
        if topic_result.coherence_score:
            sections.append(f"Coherence: {topic_result.coherence_score:.3f}\n")
        for i, terms in enumerate(topic_result.topics):
            term_str = ", ".join(t for t, _ in terms[:5])
            sections.append(f"- **Topic {i+1}**: {term_str}")
        sections.append("")

    # Network
    if cooc.edges:
        sections.append("## Keyword Co-occurrence Network\n")
        sections.append(f"Nodes: {cooc.total_keywords}  ·  Edges: {cooc.total_edges}\n")
        sections.append("| Keyword A | Keyword B | Weight |")
        sections.append("|-----------|-----------|--------|")
        for a, b, w in cooc.edges[:10]:
            sections.append(f"| {a} | {b} | {w} |")
        sections.append("")

    sections.append("\n---\n*Generated by Citationer*\n")
    return "\n".join(sections)


@app.command(name="quick")
def quick(
    output: Path = typer.Option(
        ..., "--output", "-o", help="输出文件路径 (.md 或 .html)"
    ),
    template: str = typer.Option(
        "academic", "--template", "-t", help="模板风格: academic, simple"
    ),
    enhance: bool = typer.Option(
        False, "--enhance", help="使用 LLM 增强报告（生成研究发现与展望章节）"
    ),
) -> None:
    """一键生成完整文献分析报告（Markdown/HTML）。"""
    records = _get_records()
    if not records:
        return

    console.print("[dim]正在生成报告…[/dim]")
    md = _build_markdown(records)

    # LLM enhancement
    if enhance:
        try:
            from citationer.llm.client import LLMClient, LLMConfig
            from citationer.utils.config import load_llm_config
            cfg = load_llm_config()
            if cfg["api_key"]:
                client = LLMClient(LLMConfig(
                    api_key=cfg["api_key"], model=cfg["model"],
                    base_url=cfg["base_url"],
                ))
                prompt = (
                    "Based on the bibliometric analysis above, write a "
                    "\"Research Findings and Future Outlook\" section (200-300 words) "
                    "covering key discoveries, emerging trends, and promising directions."
                )
                response = client.query(prompt, records[:50])
                md += f"\n## Research Findings and Outlook (AI-Generated)\n\n{response.content}\n"
                console.print(f"[dim]LLM 增强完成 (Token: {response.tokens_used})[/dim]")
            else:
                console.print("[yellow]LLM 未配置，跳过增强[/yellow]")
        except Exception:
            pass

    # Output
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.suffix == ".html":
        html = (
            "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n"
            "<title>Citationer Report</title>\n"
            "<style>"
            "body{font-family:Arial,sans-serif;max-width:800px;"
            "margin:0 auto;padding:20px}"
            "table{border-collapse:collapse;width:100%}"
            "td,th{border:1px solid #ddd;padding:8px}"
            "th{background:#f0f0f0}"
            "</style>\n"
            "</head>\n<body>\n"
        )
        # Convert MD to HTML (simple)
        html += md.replace("\n\n", "\n</p><p>\n").replace("\n", "<br>\n")
        html += "\n</body>\n</html>"
        output.write_text(html, encoding="utf-8")
    else:
        output.write_text(md, encoding="utf-8")

    console.print(f"[green]✅ 报告已生成: {output}[/green]")


@app.command(name="custom")
def custom(
    config_file: Path = typer.Argument(
        ..., help="报告配置 YAML 文件路径"
    ),
    output: Path = typer.Option(
        ..., "--output", "-o", help="输出文件路径"
    ),
) -> None:
    """使用自定义配置生成报告（YAML 配置文件）。"""
    records = _get_records()
    if not records:
        return

    try:
        import yaml
        cfg = yaml.safe_load(config_file.read_text(encoding="utf-8"))
    except Exception as e:
        console.print(f"[red]配置文件读取失败: {e}[/red]")
        return

    title = cfg.get("title", "Citationer Report")
    sections = cfg.get("sections", ["overview", "yearly", "journals", "authors"])
    md = f"# {title}\n\n"

    engine = StatsEngine(records)

    for sec in sections:
        if sec == "overview":
            ov = engine.overview()
            md += f"## Overview\nTotal: {ov.total_records} · h-index: {ov.h_index}\n\n"
        elif sec == "yearly":
            yr = engine.yearly()
            md += "## Yearly Trend\n\n"
            for y in sorted(yr.year_counts)[-10:]:
                md += f"- {y}: {yr.year_counts[y]}\n"
            md += "\n"
        elif sec == "journals":
            jr = engine.journals(top_n=10)
            md += "## Top Journals\n\n"
            for i, (n, c) in enumerate(jr.items, 1):
                md += f"{i}. {n} ({c})\n"
            md += "\n"
        elif sec == "authors":
            ar = engine.authors(top_n=10)
            md += "## Top Authors\n\n"
            for i, (n, c) in enumerate(ar.top_authors.items, 1):
                md += f"{i}. {n} ({c})\n"
            md += "\n"
        elif sec == "keywords":
            te = TextEngine(records)
            kw = te.keywords(top_n=10)
            md += "## Keywords\n\n"
            for kw_name, cnt in kw.top_keywords:
                md += f"- {kw_name}: {cnt}\n"
            md += "\n"
        elif sec == "topics":
            te = TextEngine(records)
            tp = te.topics(num_topics=5)
            md += "## Topic Modeling\n\n"
            for i, terms in enumerate(tp.topics):
                md += f"- Topic {i+1}: {', '.join(t[0] for t in terms[:5])}\n"
            md += "\n"

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(md, encoding="utf-8")
    console.print(f"[green]✅ 报告已生成: {output}[/green]")
